# Generated by Django 5.0 on 2023-12-23 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='size',
            field=models.CharField(choices=[('US 5', 'US 5'), ('US 5.5', 'US 5.5'), ('US 6', 'US 6'), ('US 6.5', 'US 6.5'), ('US 7', 'US 7'), ('US 7.5', 'US 7.5'), ('US 8', 'US 8'), ('US 8.5', 'US 8.5'), ('US 9', 'US 9'), ('UK 3', 'UK 3'), ('UK 3.5', 'UK 3.5'), ('UK 4', 'UK 4'), ('UK 4.5', 'UK 4.5'), ('UK 5', 'UK 5'), ('UK 5.5', 'UK 5.5'), ('UK 6', 'UK 6'), ('UK 6.5', 'UK 6.5'), ('UK 7', 'UK 7'), ('UK 7.5', 'UK 7.5'), ('UK 8', 'UK 8'), ('UK 8.5', 'UK 8.5'), ('UK 9', 'UK 9')], default='UK 3', max_length=100),
        ),
    ]
